# Generated by Django 4.0 on 2022-01-16 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_rename_catagory_room_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='User',
            new_name='user',
        ),
    ]
